#
#Thu Oct 08 10:19:10 CST 2026
downloadedAt=Thu Oct 08 10\:19\:10 CST 2026
url=https\://raw.githubusercontent.com/GTNewHorizons/ExampleMod1.7.10/0.2.2/gtnhShared/spotless.eclipseformat.xml
version=1
