
name: Build and test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, main, 29x ]
  push:
    branches: [ master, main, 29x, 'fix/**' ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
